### ISSUE TITLE
可否将思源黑体、思源宋体这两个开源的字体也当成默认字体

### ISSUE THREAD

**Issue by maptile** [tumashu/cnfonts#100]
目前思源黑体和思源宋体包含的字符很多，而且是开源的。能否考虑纳入到中文默认字体列表中，以便喜欢这两个字体的人使用。

谢谢

**Comment by tumashu** [comment]
用 cnfonts-insert-fontname 测试一下字体名称， 然后告诉我，我加进去

**Comment by tumashu** [comment]
试了一下，个人感觉这个字体不太好看，已添加

**Comment by maptile** [comment]
十分感谢

**Comment by maptile** [comment]
我更新了cnfonts，确实看到了您添加的几个字体。但在我的系统中仍然显示为NA。

我的系统是Ubuntu 18.10，界面英文。

在我这里使用cnfonts-insert-fontname得到的结果如下：         
"Source Han Sans SC" 思源黑体
"Source Han Serif SC"  思源宋体

**Comment by tumashu** [comment]
ok

**Comment by maptile** [comment]
更新了，已经OK了，谢谢。
