### ISSUE TITLE
加不了英文字号

### ISSUE THREAD

**Issue by tangxinfa** [tumashu/cnfonts#101]
修改 `~/emacs.d/cnfonts/v4/Programming.el` 中的英文字号（如：`11.5` 改成 `11` ），如下

`(11.5 14.0 14.0)` 改为 `(11 14.0 14.0)`

`cnfonts-edit-profile` 后对齐页面上 `11` 号字段就不显示了，这个怎么弄？

**Comment by tumashu** [comment]
cnfonts 目前不支持 11 号字体

**Comment by tumashu** [comment]
这个应该解决了

**Comment by tangxinfa** [comment]
确认已经支持，先在 `cnfonts--fontsizes-fallback` 变量中加入 11 字号就可以了。

**Comment by tumashu** [comment]
我刚刚加了，不用你设置这个变量了。
