### ISSUE TITLE
`cnfonts-config-filename`不能设置成绝对路径

### ISSUE THREAD

**Issue by isolet** [tumashu/cnfonts#103]
设置成绝对路径，在switch profile的时候会报错。因为我用`no-littering`管理配置文件，`no-littering-expand-etc-file-name`会将文件展开成绝对路径，然后再`setq`就报错了。

    cnfonts--save-config-file: Opening output file: No such file or directory, /Users/user/.emacs.d/private/chinese-fonts-setup/Users/user/.emacs.d/savefile/etc/cnfonts.conf

这个文件一定要放在`cnfonts（或chinese-fonts-setup）`这个文件夹里吗？主要不想将入git的文件与这个不入git的文件放在一起，而放在某savefiles文件夹里。

**Comment by tumashu** [comment]
你这种情况设置 cnfonts-directory

**Comment by isolet** [comment]
设置这个有区别吗。。😂profile和那个cnfonts.conf还是要放在一起

**Comment by tumashu** [comment]
因为两个文件都是 cnfonts 的配置，当然要放到一起了

**Comment by isolet** [comment]
好吧…主要是那个cnfonts.conf每次改文件内容都要变…
