### ISSUE TITLE
中英文对齐后能使用ditaa 吗？

### ISSUE THREAD

**Issue by brioglade** [tumashu/cnfonts#105]
大家谁用了cnfonts 后，使用ditaa 能画含有中英文的图了吗？

**Comment by tumashu** [comment]
中英文对齐的图，生成图片后，可能就对不齐了

**Comment by brioglade** [comment]
https://tamura70.hatenadiary.org/entry/20100317/org
https://www.johf.com/log/20130113a.html这个日语是怎么做到的呢？

**Comment by tumashu** [comment]
第一种方式看起来是更改 ditaa 的代码的吧？
