### ISSUE TITLE
与窗口最大化脚本的兼容问题

### ISSUE THREAD

**Issue by OldIMP** [tumashu/cnfonts#109]
我一直在用下面的脚本来让emacs启动时自动最大化：
```elisp
(add-to-list 'default-frame-alist '(fullscreen . maximized))
```
但是用了cnfonts之后就会变成一个小窗口：
```elisp
(frame-native-height)
-> 1288
(frame-native-width)
-> 1629
```
而手动最大化之后的大小是：
```elisp
(frame-native-height)
-> 2004
(frame-native-width)
-> 3840
```
我用的是Windows 10 Pro v1909 OS build 18363.592, "GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29"

请问高手知道大概问题可能在哪吗？非常感谢！这个包解决了我多年的中文字体问题。

**Comment by tumashu** [comment]
cnfonts-keep-frame-size 设置为 nil试试
