### ISSUE TITLE
在 macOS 下找到不花园明朝字体

### ISSUE THREAD

**Issue by exaos** [tumashu/cnfonts#110]
确认花园明朝字体已经安装，但默认设置中列的几种字体在 macOS 下都找不到：
`("HanaMinB" "SimSun-ExtB" "MingLiU-ExtB" "PMingLiU-ExtB" "MingLiU_HKSCS-ExtB")`

经检查，是因为字体名称在不同系统中显示不同。在 macOS 下，花园明朝字体显示为如下：
```
"Hanazono Mincho"
"Hanazono Mincho A"
"Hanazono Mincho B"
"Hanazono Mincho C"
"Hanazono Mincho Ex"
"Hanazono Mincho Ex A1"
"Hanazono Mincho Ex A2"
"Hanazono Mincho Ex B"
"Hanazono Mincho Ex C"
"Hanazono Mincho I"
```
将如上的字体名称加入列表即可。其中的 A-C, I, Ex xx 包含不同字符集。

**Comment by tumashu** [comment]
Fixed
