### ISSUE TITLE
每次改变theme，或者重启，字体都需要重新设置 

### ISSUE THREAD

**Issue by eitazhou** [tumashu/cnfonts#111]
使用spacemacs，在初始设置文件.spacemacs下的`dotspacemacs/user-config ()`函数中设置：
`(use-package cnfonts
   :init
   (add-hook 'after-init-hook #'cnfonts-enable)
   (add-hook 'after-make-frame-functions #'cfs-set-font-with-saved-step)
   ;;(add-hook 'window-setup-hook #'cfs-set-font-with-saved-step)
   :config
   (
    cnfonts-enable)
   (setq cnfonts-keep-frame-size nil)
   (setq cnfonts-use-face-font-rescale t) ;;使用 org-mode 时，让不同的标题，使用的字体大小也不同
   (setq cnfonts-use-cache t)
   (setq cnfonts-profiles
         '( "org-mode" "program" ))
   ;;(setq cnfonts--profiles-steps '(("org-mode" . 8) ("program" . 7)))

   )`

使用M-x `cnfonts-edit-profile`可以做到中英文对齐，但改变theme或重启后好像中英文对齐的设置没有保存，需要重新再M-x `cnfonts-edit-profile`设置一次。有点麻烦，可以在.spacemacs中直接定义好吗？

**Comment by tumashu** [comment]
不需要这么弄，profile设置好之后，已经自动保存到硬盘了，有一个命令直接调用就可以恢复设置，不需要重复设置

在 2020-03-08 16:37:58，eitazhou <notifications@github.com> 写道：


使用spacemacs，在初始设置文件.spacemacs下的dotspacemacs/user-config ()函数中设置：
`(use-package cnfonts
:init
(add-hook 'after-init-hook #'cnfonts-enable)
(add-hook 'after-make-frame-functions #'cfs-set-font-with-saved-step)
;;(add-hook 'window-setup-hook #'cfs-set-font-with-saved-step)
:config
(
cnfonts-enable)
(setq cnfonts-keep-frame-size nil)
(setq cnfonts-use-face-font-rescale t) ;;使用 org-mode 时，让不同的标题，使用的字体大小也不同
(setq cnfonts-use-cache t)
(setq cnfonts-profiles
'( "org-mode" "program" ))
;;(setq cnfonts--profiles-steps '(("org-mode" . 8) ("program" . 7)))

)`

使用M-x cnfonts-edit-profile可以做到中英文对齐，但改变theme或重启后好像中英文对齐的设置没有保存，需要重新再M-x cnfonts-edit-profile设置一次。有点麻烦，可以在.spacemacs中直接定义好吗？

**Comment by tumashu** [comment]
cfs-set-font-with-saved-step 可能这个运行时机不对

在 2020-03-08 16:37:58，eitazhou <notifications@github.com> 写道：


使用spacemacs，在初始设置文件.spacemacs下的dotspacemacs/user-config ()函数中设置：
`(use-package cnfonts
:init
(add-hook 'after-init-hook #'cnfonts-enable)
(add-hook 'after-make-frame-functions #'cfs-set-font-with-saved-step)
;;(add-hook 'window-setup-hook #'cfs-set-font-with-saved-step)
:config
(
cnfonts-enable)
(setq cnfonts-keep-frame-size nil)
(setq cnfonts-use-face-font-rescale t) ;;使用 org-mode 时，让不同的标题，使用的字体大小也不同
(setq cnfonts-use-cache t)
(setq cnfonts-profiles
'( "org-mode" "program" ))
;;(setq cnfonts--profiles-steps '(("org-mode" . 8) ("program" . 7)))

)`

使用M-x cnfonts-edit-profile可以做到中英文对齐，但改变theme或重启后好像中英文对齐的设置没有保存，需要重新再M-x cnfonts-edit-profile设置一次。有点麻烦，可以在.spacemacs中直接定义好吗？

**Comment by eitazhou** [comment]
试了一下，将(setq cnfonts-use-cache t)注释掉，ok了。看帮助，`cnfonts-use-cache`这个变量设置为t，很有可能会让 cnfonts 调整字体的功能失效。`cfs-set-font-with-saved-step ` 那一句也注释掉了。谢谢！
