### ISSUE TITLE
对齐设置不起效果

### ISSUE THREAD

**Issue by yatsky** [tumashu/cnfonts#113]
Hi,
我的 cnfonts 原来可以正常使用（WSL + X window)，后来运行了 `apt-get update` `apt-get upgrade'之后，cnfonts 能够正常启动，也可以正常设置字体，但是在对齐的时候，调整数字没有任何效果。
截图里已经把中文调整到了28但是依然没有用（表格一直没有变过）。不太清楚这个应该怎么解决。
谢谢！

![image](https://user-images.githubusercontent.com/9735384/77216923-056daa80-6b6a-11ea-84ff-3a9291976bf7.png)

**Comment by tumashu** [comment]
很有可能是cnfonts没有识别出你的字体，emacs默认设置了一个字体

**Comment by tumashu** [comment]
点中文按钮看看哪个字体生效了

**Comment by yatsky** [comment]
英文的：
![image](https://user-images.githubusercontent.com/9735384/77218885-eed04f00-6b7b-11ea-95a4-7653d5d893b9.png)
中文的：
![image](https://user-images.githubusercontent.com/9735384/77218892-027bb580-6b7c-11ea-98b1-af8549940e86.png)
EXT-B
![image](https://user-images.githubusercontent.com/9735384/77218895-158e8580-6b7c-11ea-8e71-f8c7ba0135c4.png)

**Comment by tumashu** [comment]
看起来很奇怪，换个其它中文字体试试

**Comment by yatsky** [comment]
感谢，现在可以了。我原来已经装了其他字体（包括微软雅黑），但是字体名字跟`cnfonts--custom-set-fontnames` 里的不一样，在 ui 里显示没有安装。我把`cnfonts--custom-set-fontnames`里面的字体名字改了之后，在 ui 里换成了微软雅黑就可以了。

**Comment by tumashu** [comment]
你可以提交一个是pr，把这个名字添加进cnfonts，以后也就方便了
