### ISSUE TITLE
中文字体列表出现一堆字体，还有字体选择问题。

### ISSUE THREAD

**Issue by feileb** [tumashu/cnfonts#116]
![选区_653](https://user-images.githubusercontent.com/10227741/78637648-640e8480-78dd-11ea-8cd8-6f39b8ce1971.png)
源文件中的(setq cnfonts--custom-set-fontnames)中删除了这些字体也没有用，在edit profile的时候还是会出来，很多字体（微软、方正、汉仪、长城等），我也没有安装这些字体，不知道是哪里来的。

另外字体列表里面没有noto sans mono字体，手动添加到源文件中才可以选择。但是在对齐里面，英文，ext-b都可以调整大小对齐。中文字体如果选择noto sans mono则无法对齐。

**Comment by tumashu** [comment]
可能你添加的 note san mono 字体名称有问题

**Comment by tumashu** [comment]
这些字体名称是 cnfonts 自带的 fallback， 签名 NA 说明你系统中没有这个字体

**Comment by feileb** [comment]
> 可能你添加的 note san mono 字体名称有问题

是的，我也发现可能跟字体名有关，我做了如下测试：
1，不启动cnfonts，使用spacemacs的字体配置，字体改变了，但是describe-char查看字体名也不对。
```
dotspacemacs-default-font '("Noto Sans Mono"
                               :size 15
                               :weight normal
                               :width normal)
```
![选区_655](https://user-images.githubusercontent.com/10227741/78643100-501b5080-78e6-11ea-803a-ab2e193b8113.png)


2，启动cnfonts，配置中文为"Noto Sans Mono"，describe-char显示是HanaMinA字体
![选区_654](https://user-images.githubusercontent.com/10227741/78642496-67a60980-78e5-11ea-940c-75415c04a51b.png)

**Comment by ProMachine** [comment]
同样几乎所有字体都是NA而且不是NA的部分也有问题。参考其他中文字体配置，用的是family而不是name，仿照生成出的代码自己定义能成功，但是没办法导出实现对齐的代码
还有一个问题，使用(cl-prettyprint (font-family-list))输出的中文乱码，emacs新手，似乎试过utf和gbk，但没用⋯
![image](https://user-images.githubusercontent.com/22593803/106218038-7ca3ae80-6211-11eb-8844-7c5978f53078.png)

**Comment by ProMachine** [comment]
已部分解决，没有配置cnfonts路径，需要在.emacs.d/cnfonts/v4中添加字体才行，在cnfonts.el中配置没用，不少人遇到这个问题，可以补一下说明。
另外不知道scratch中编码是utf-8也没用，(cl-prettyprint (font-family-list))，不知道是程序问题还是buffer问题，还有各种coding system，光utf-8就那么多版本，晕了⋯

**Comment by tumashu** [comment]
最新版本的cnfonts只保留少量中文字体作为fallback
