### ISSUE TITLE
cnfonts-personal-fontnames 加不到中文列表里面？

### ISSUE THREAD

**Issue by LambdaXIII** [tumashu/cnfonts#117]
我添加了一些字体，使用的 fc-list 查看的名称
然后profile设置界面上英文列表里有，也能正常加载
但是中文列表里没得

目前我是手动编辑了 profile 里的列表暂时解决的

是否是一个 bug？还是说另外两个列表有别的办法设置？

**Comment by tumashu** [comment]
是不是你设置不正确，这个变量是三个list组成的list, 对应英文，中文，extb

**Comment by LambdaXIII** [comment]
哎呀对不起是我错了，我以为这个变量是一个列表。
Readme里面好多写的都不是很清楚，我也在摸索……
