### ISSUE TITLE
提示cnfonts--get-current-profile: Symbol’s value as variable is void: cnfonts-profiles-directory

### ISSUE THREAD

**Issue by maptile** [tumashu/cnfonts#118]
系统：Ubuntu 20.04
Emacs：GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14) of 2020-03-26, modified by Debian
今天升级了一下Emacs组件，突然发现启动时，提示Symbol’s value as variable is void: cnfonts-profiles-directory

cnfonts版本为：cnfonts-20200529.619

尝试删除.emacs.d/cnfonts目录，无效
尝试删除cnfonts，重装，依然是这个提示。

我看到在 https://github.com/tumashu/cnfonts/commit/451ac2977641eeca96bad643c1d1d807efbc3f93 中删除了这个变量，所以问题可能就是这里了。

**Comment by tumashu** [comment]
应该修复了，再试试吧，汗。。。。

**Comment by maptile** [comment]
安装新版后，问题解决。非常感谢。
