### ISSUE TITLE
windows doom emacs编译问题

### ISSUE THREAD

**Issue by Gonw** [tumashu/cnfonts#121]
查看issue之前也有类似问题#29，git更新后编译会有问题
```
       Building cnfonts...
x There was an unexpected error:
  Type: error
  Message:
    error
  Data:
    "cnfonts-ui.el:0:0: error: error: (Local variables entry is missing the suffix)"
```

临时解决办法
将cnfonts-ui.el中的^M删除即可编译成功

估计是checkout windows checkin linux的设置造成的，
不过我看其它的包也都有^M，都可以编译成功，估计还是和中文有关

---------------------------------------
linux下没这个问题。

**Comment by tumashu** [comment]
```
;; Local Variables:
;; coding: utf-8-unix
;; End:
```
我把这个删除了，你再试试，如果还不行，那估计就是 doom 的问题了

**Comment by Gonw** [comment]
今天更新编译已经没有问题了，多谢
