### ISSUE TITLE
配置cnfonts-enable后，配置文件中的设置全屏模式失效

### ISSUE THREAD

**Issue by ArkiZh** [tumashu/cnfonts#122]
- 为了启动后直接全屏显示，我的文件中加有` (setq initial-frame-alist (quote ((fullscreen . maximized))))`。
- 在启动文件中加入(cnfonts-enable)之后，emacs启动时候会先全屏闪一下，之后界面就缩小了
- 缩小后我注意到右上角最大化的图标是激活状态。

希望在配置完文字后，不干扰窗口尺寸。

**Comment by tumashu** [comment]
cnfonts-keep-frame-size 设置为 nil 试试

**Comment by ArkiZh** [comment]
加上这个`(setq cnfonts-keep-frame-size nil)`打开之后是全屏的，但是打开过程看到：
1. 界面先是emacs默认大小的
2. 再之后连字带界面一起缩小了
3. 再之后变全屏了

中间第2步缩小的过程可以去掉吗？
还有，感觉这个变量的描述没看太懂，主要什么时候起作用的呀？启动时候设置成nil，对之后有什么影响吗？
