### ISSUE TITLE
伟大的作者，你这神器可以在tty模式下运行吗？

### ISSUE THREAD

**Issue by xukongwen** [tumashu/cnfonts#126]
好似貌似不行，但是能支持吗？
谢谢！

**Comment by tumashu** [comment]
可以，不过不能使用 posframe， 用 popup 或者 minibuffer 就可以

**Comment by tumashu** [comment]
tty 中英文对齐很简单，不需要这个包

**Comment by benluo** [comment]
tty和gui的字体机制不一样，没办法的。

**Comment by xukongwen** [comment]
> tty 中英文对齐很简单，不需要这个包

现在我有个奇怪问题
就是安装的中文字体后，字距不知为啥拉开的特别大，比较难看，英文倒是合适。
我用的fbterm，也不知道能不能调整。

谢谢！

**Comment by tumashu** [comment]
肯定可以，找找fbterm的字体设置
