### ISSUE TITLE
请问如何使用不同字重？

### ISSUE THREAD

**Issue by huangzichen** [tumashu/cnfonts#127]
感谢开发这个插件解决了中英文字体显示问题🙏🏻️
我英文字体使用`Source Code Pro`, 希望使用`Semibold`字重, 尝试添加`Source Code Pro Semibold`到`cnfonts-personal-fontnames` 和 profile 里, 添加之后在`cnfonts-edit-profile`能正确显示该字体, 但是单击切换字重并没有改变.

**Comment by tumashu** [comment]
这个估计支持不了

**Comment by jsntn** [comment]
> 感谢开发这个插件解决了中英文字体显示问题🙏🏻️ 我英文字体使用`Source Code Pro`, 希望使用`Semibold`字重, 尝试添加`Source Code Pro Semibold`到`cnfonts-personal-fontnames` 和 profile 里, 添加之后在`cnfonts-edit-profile`能正确显示该字体, 但是单击切换字重并没有改变.

试试直接安装 Source Code Pro Semibold 字体？
