### ISSUE TITLE
如何切换到指定的profile

### ISSUE THREAD

**Issue by wowhxj** [tumashu/cnfonts#129]
感谢作者，这个包非常好用，解决了我在emacs下讲ppt时的中英文字体同步缩放的问题，现在试用`org-tree-slide`进行播放PPT时，表格不会对不齐了，org-mode的headline上的中文也都可以放大了。

这里咨询一个问题，`cnfonts`如何切换到指定的profile？我看到`cnfonts-switch-profile`函数是没有参数的，调用后需要用户自己选择profile1, profile2, profile3。那如何在配置文件里直接切换到指定的profile（如profile2）呢？（这个需求来源于，我想写一个org-tree-slide的hook，在启动org-tree-slide-mode的时候，自动切换到profile2，再结束的时候，再切换回profile1）

我现在用了一个笨方法解决，通过设置`cnfonts-profiles`，将profile3删除，然后使用 `cnfonts-next-profile`函数来切换。但总觉得这不是正确的做法。请教一下如何实现这个需求？感激不尽！

**Comment by tumashu** [comment]
cnfonts--current-profile-name

**Comment by wowhxj** [comment]
在`emacs-china.org`论坛上有坛友提示使用`(cnfonts--select-profile "profile1")`函数来实现，经验证完全可行。

也感谢你的回复！

close this.

**Comment by zhangjie2012** [comment]
```
(if (eq system-type 'darwin)
	  (setq cnfonts--select-profile "profile1"))
  (if (eq system-type 'windows-nt)
	  (setq cnfonts--select-profile "profile2"))
  (if (eq system-type 'gnu/linux)
	  (setq cnfonts--select-profile "profile3"))
```
针对不同的系统设置不同的 profile 不生效，只会选择 cnfonts.conf 中第一个 profile。

是我的用法有问题吗？
