### ISSUE TITLE
使用 cnfonts 生成的 snippet, 放入 .emacs 里面启动加载，当使用 emacs --daemon 模式时，总是失败。

### ISSUE THREAD

**Issue by zw963** [tumashu/cnfonts#130]
举个例子，这是 cnfonts 为我生成的 config

```cl
;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
(set-face-attribute
 'default nil
 :font (font-spec :name "-CTDB-Fira Code-normal-normal-normal-*-*-*-*-*-d-0-iso10646-1"
                  :weight 'normal
                  :slant 'normal
                  :size 12.5))
(dolist (charset '(kana han symbol cjk-misc bopomofo))
  (set-fontset-font
   (frame-parameter nil 'font)
   charset
   (font-spec :name "-LXGW-霞鹜文楷等宽-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1"
              :weight 'normal
              :slant 'normal
              :size 15.0)))
```

如果我直接使用这段代码，然后重新启动 emacs daemon.

emacs --daemon, 会立即报错。

```
Warning (initialization): An error occurred while loading ‘/home/zw963/.emacs’:

error: Fontset ‘tty’ does not exist
```

解决办法是，为第二段 dolist 的代码外面报一个 when.

```cl
(when (display-graphic-p)
  (dolist (charset '(kana han symbol cjk-misc bopomofo))
    (set-fontset-font
     (frame-parameter nil 'font)
     charset
     (font-spec :name "-LXGW-霞鹜文楷等宽-normal-normal-normal-*-*-*-*-*-*-0-iso10646-1"
                :weight 'normal
                :slant 'normal
                :size 15.0))))
```

**Comment by tumashu** [comment]
我试着修复了一下，你再试试看行不行

**Comment by zw963** [comment]
非常感谢你，我将之前的问题统一再整理一下。

### 已经修复的问题：

 生成的代码已经可以直接被使用而不会在 emacs --daemon 下面报错了。


### 仍然存在的问题1：

1.  当我在使用 cnfonts-edit-profile 功能时，我现在正在调整 14 18 这个配置，我觉得大小还不错，也对齐了。正如下面这个样子。

![image](https://user-images.githubusercontent.com/549126/139590036-67a79d69-4b92-4351-8e76-32e6c8d63f9d.png)

2. 然后我点击 “对齐设置完成”，正如你看到的，字体整体又变小了。

![image](https://user-images.githubusercontent.com/549126/139590041-2d0eda2b-7c38-4305-865c-a2ac19a85335.png)

然后检查生成的 snippets, 会发现它生成的还是 12.5,  15 的那个. 也许是我不会用，这个生成的 snippet 如果在配置文件里直接用，（同时关闭 cnfonts), 会发现，字体显示效果和在 cnfonts-edit-profile 里面通过 test 看到的 12.5 15  的那个效果完全不一样，明显比 test 里面显示的字体小好多, 这正好引出下一个问题。

### 仍然存在的问题2

生成的 snippet 在 daemon 模式下还是不工作。举个例子：我有如下 config:

```cl
(when (display-graphic-p)
  (set-face-attribute
   'default nil
   :font (font-spec :name "Fira Code"
                    :weight 'normal
                    :slant 'normal
                    :size 14))
  (dolist (charset '(kana han symbol cjk-misc bopomofo))
    (set-fontset-font
     "fontset-default"
     charset
     (font-spec :name "霞鹜文楷等宽"
                :weight 'normal
                :slant 'normal
                :size 18.0)))
  )
```

然后我重启 emacs daemon, 之后，看起来是这个样子。

![image](https://user-images.githubusercontent.com/549126/139590267-c2458d80-c96e-4752-b1e5-a597d000689b.png)

但是我如果 eval buffer 之后， 结果效果就不一样了 （这个结果应该和正常的 emacs 启动后显示效果一样）

![image](https://user-images.githubusercontent.com/549126/139590300-d02ec672-427b-491f-8173-f348a00d8242.png)

另外，在做了这个 diff 之后，我发现其实已经不需要 (when (display-graphic-p) , daemon 模式下也不会报错了。

```diff
- (frame-parameter nil 'font)
+     \"fontset-default\"
```

### 仍然存在的问题 3  （也许这个不算 issue?)

就算像 emacs 上面正常启动一样，我 eval buffer 之后, 生成的 snippet 仍然无法让表格对齐。

![image](https://user-images.githubusercontent.com/549126/139591413-32cef583-0848-4130-aaa9-82c52f65f9a1.png)

但是如果开启 cnfonts,  默认选择的字体大小、还有对齐都很满意的，比使用上面的 snippets 好看多了。

但是，老实讲，我有个疑问，很困惑，我通过 cnfonts-edit-profile 编辑半天，不同的字体组合都对齐了，并且保存配置文件到  profile1 文件，然后当我以如下配置文件启动我的 Emacs 的时候，他到底选择的是下面字体组合而那个组合方案？

```cl
(require 'cnfonts)
(require 'cnfonts-ui)

(setq cnfonts-use-face-font-rescale t)
(setq cnfonts-directory (expand-file-name "configs" (file-name-directory (or load-file-name buffer-file-name))))

(cnfonts-enable)

```

这是我生成的 profile1 文件。（我猜测每次启动时会加载它)

[configs.zip](https://github.com/tumashu/cnfonts/files/7449187/configs.zip)

**Comment by tumashu** [comment]
```
然后我点击 “对齐设置完成”，正如你看到的，字体整体又变小了。
```
我把这个按钮名字改了一下，应该更具体了， 对齐设置是为了获取不同字号的对齐映射表，设置完成之后，当然是要恢复到平时使用的默认字号了，这个字号是用 cnfonts-increase-fontsize 和 cnfonts-decrease-fontsize 来控制的

**Comment by tumashu** [comment]
```
在 daemon 模式下还是不工作
```
daemon模式下，frame创建延迟，所以需要把字体设置放到下面两个hook才能生效
```
1. `after-make-frame-functions'
2. `window-setup-hook'

```

**Comment by tumashu** [comment]
```
但是，老实讲，我有个疑问，很困惑，我通过 cnfonts-edit-profile 编辑半天，不同的字体组合都对齐了，并且保存配置文件到 profile1 文件，然后当我以如下配置文件启动我的 Emacs 的时候，他到底选择的是下面字体组合而那个组合方案？
```
(cnfonts--get-valid-fonts)

**Comment by zw963** [comment]
奇怪了，应该不应该啊，但是下面的代码在 Emacs 28.0.60 下面还是不工作：

```cl
(defun set-cnfonts-fonts(&optional frame)
  (interactive)
  (when (display-graphic-p)
    (set-face-attribute
     'default nil
     :font (font-spec :name "Fira Code"
                      :weight 'normal
                      :slant 'normal
                      :size 14))
    (dolist (charset '(kana han symbol cjk-misc bopomofo))
      (set-fontset-font
       "fontset-default"
       charset
       (font-spec :name "霞鹜文楷等宽"
                  :weight 'normal
                  :slant 'normal
                  :size 18.0)))))

(add-hook 'window-setup-hook 'set-cnfonts-fonts t)

(if (and (fboundp 'daemonp) (daemonp))
    (add-hook 'after-make-frame-functions 'set-cnfonts-fonts t)
  )
```

然后，如果移除了 (when (display-graphic-p) ...) 就工作了。

```cl
(defun set-cnfonts-fonts(&optional frame)
  (interactive)
  ;; (when (display-graphic-p)
    (set-face-attribute
     'default nil
     :font (font-spec :name "Fira Code"
                      :weight 'normal
                      :slant 'normal
                      :size 14))
    (dolist (charset '(kana han symbol cjk-misc bopomofo))
      (set-fontset-font
       "fontset-default"
       charset
       (font-spec :name "霞鹜文楷等宽"
                  :weight 'normal
                  :slant 'normal
                  :size 18.0))))
;; )

(add-hook 'window-setup-hook 'set-cnfonts-fonts t)

(if (and (fboundp 'daemonp) (daemonp))
    (add-hook 'after-make-frame-functions 'set-cnfonts-fonts t)
  )
```

**Comment by zw963** [comment]
另外，在做了这个 diff 之后，我发现其实已经不需要 (when (display-graphic-p) , daemon 模式下也不会报错了。

```diff
- (frame-parameter nil 'font)
+     \"fontset-default\"
```

因为现在已经不报错了，所以，现在生成的 snippet 似乎不需要包在 (when (display-graphic-p) 里面了？
而且，我们应该生成一个所有情况下 (daemon 或 非daemon) 都可用的 snippet,  你认为呢？

然后，现在应该就只剩下问题 3 表格对齐的问题了。我用的 emacs 28 master 分支，是不是这个问题？

> (cnfonts--get-valid-fonts t)

我的意思是它到底选择的那个 “大小的组合” 呢？我感觉它应该是 12.5 那个，再请教一下，我的个人配置里并没有任何地方设置使用 12.5 那个，事实上，根本都没有字体配置，除了 cnfonts, 那么自动选择这个(结果其实非常不错)到底是基于什么判断呢？

**Comment by tumashu** [comment]
cnfonts.conf中记录的数字是当前step,  通过这个step数来确定

**Comment by tumashu** [comment]
而且，我们应该生成一个所有情况下 (daemon 或 非daemon) 都可用的 snippet, 你认为呢

我添加了一个注意事项，提醒一下用户，不做进一步展开。

**Comment by zw963** [comment]
多谢，感觉各方面给用户的体验，提高了不少。

就剩下用 snippet 的时候，表格对齐的问题了，如果这个不算是问题, 可以关掉这个 issue 了。

**Comment by zw963** [comment]
BTW:  when use with emacs 28, get following warning:

cnfonts.el:1028:20: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode'

could you please fix it with named arguments?

**Comment by tumashu** [comment]
这个我暂时不知道怎么处理，如果换成新的方式，是不是就不能在旧版本的 emacs 上使用了？

**Comment by zw963** [comment]
> 这个我暂时不知道怎么处理，如果换成新的方式，是不是就不能在旧版本的 emacs 上使用了？

这个不用考虑吧。命名的方式定义 minor-mode 应该早在 emacs 21 就支持了吧？支持好几十年了？

![image](https://user-images.githubusercontent.com/549126/139788709-d30d80b7-3f05-46e3-8069-a417ec574d85.png)

您可以参照我这个 PR 改一下。

https://github.com/mattfidler/auto-indent-mode.el/pull/68/files

**Comment by tumashu** [comment]
```
这个不用考虑吧。命名的方式定义 minor-mode 应该早在 emacs 21 就支持了吧？支持好几十年了？
```
Fixed.

**Comment by zw963** [comment]
除了使用 snippet 表格无法对齐，其他问题都解决了，多谢！
