### ISSUE TITLE
使用 cnfonts 生成的 snippets 作为 .emacs.d 配置文件，并且不再 (require 'cnfonts),  org 表格无法对齐。

### ISSUE THREAD

**Issue by zw963** [tumashu/cnfonts#131]

**Comment by tumashu** [comment]
我试着修复了一下，也许有用

**Comment by tumashu** [comment]
生成snippet的功能已经去掉，所以这个issue关闭了

**Comment by zw963** [comment]
不知道你改了什么，我发现那个手动编辑的模式没有了，而且，自定义字体 （我扔到 ~/.local/share/cnfonts 里面的字体），现在也用不了了。

**Comment by zw963** [comment]
*ERROR*: Font not available: #<font-spec nil nil Fira\ Code\ Retina nil nil bold nil nil 12.5 nil nil nil ((:name . "Fira Code Retina:style=Retina") (:style . Retina))>

**Comment by zw963** [comment]
下面的这些字体都用不了了。

```sh
 ╰─ $ fc-list |grep Fira
/home/zw963/.local/share/fonts/FiraCode/FiraCode-Medium.ttf: Fira Code,Fira Code Medium:style=Medium,Regular
/home/zw963/.local/share/fonts/FiraCode/FiraCode-Regular.ttf: Fira Code:style=Regular
/home/zw963/.local/share/fonts/FiraCode/FiraCode-Bold.ttf: Fira Code:style=Bold
/home/zw963/.local/share/fonts/FiraCode/FiraCode-Retina.ttf: Fira Code,Fira Code Retina:style=Retina,Regular
/home/zw963/.local/share/fonts/FiraCode/FiraCode-Light.ttf: Fira Code,Fira Code Light:style=Light,Regular
/home/zw963/.local/share/fonts/FiraCode/FiraCode-SemiBold.ttf: Fira Code,Fira Code SemiBold:style=SemiBold,Regular
```

**Comment by zw963** [comment]
哦，好吧，我用字体名称，例如： `FiraCode-Retina` 可以工作了，但是目前只能自己手动改 configs/v4/profile1.el, 手动加入字体，如果默认打开运行 `confonts-edit-profile`, 就可以读取到这些字体，就再好不过了。

**Comment by tumashu** [comment]
cnfonts-personal-fontnames 用这个变量试试

**Comment by tumashu** [comment]
手动编辑模式去掉了，两个模式维护起来太费事

**Comment by zw963** [comment]
> cnfonts-personal-fontnames 用这个变量试试

我加了。

```cl
(defconst cnfonts-personal-fontnames
  '(;; 英文字体
    ("FiraCode-Retina")
    ;; 中文字体
    ("霞鹜文楷等宽")
    ;; EXT-B 字体
    ()
    ;; Symbol 字符字体
    ()
    ;; Emacs 社区配置中，用于装饰的字符使用的字体
    ()))
```

列表中倒是显示出来字体了，但是点选后出错，

[cnfonts]: 系统没有安装字体: "FiraCode-Retina" .

**Comment by tumashu** [comment]
Fira Code Retina 这个名称行不行？

**Comment by zw963** [comment]
> 



> Fira Code Retina

set-face-font: Font not available: #<font-spec nil nil Fira\ Code\ Retina nil nil bold nil nil 12.5 nil nil nil ((:name . "Fira Code Retina"))>

**Comment by tumashu** [comment]
我试着修复了一下，试试最新代码吧

**Comment by tumashu** [comment]
不过可能会带来其它问题，因为好像有人提过，我忘记了

**Comment by zw963** [comment]
字体好复杂啊，

Fira Code Retina  => 可以设置成功了，但是无效

 FiraCode-Retina => 无法设置成功，但是我手动编辑后，可以工作。

**Comment by zw963** [comment]
> 我试着修复了一下，试试最新代码吧

Fira Code Retina 这个可以了，酷！

**Comment by zw963** [comment]
> 不过可能会带来其它问题，因为好像有人提过，我忘记了

问题我知道了，再点击系统字体，例如，想换回微软雅黑，又是一样的错误。

[cnfonts]: 系统没有安装字体: "？？？" .

**Comment by tumashu** [comment]
能不能截个图看看，有点蒙圈

**Comment by zw963** [comment]
刚才我通过鼠标点击的方式，已经正确的选择了我的 $HOME 下的字体。

![image](https://user-images.githubusercontent.com/549126/147408520-20605269-d5f4-45f1-b4e7-973584b5dc90.png)

![image](https://user-images.githubusercontent.com/549126/147408537-1bc4b968-f5c6-420f-81a9-d718d46ab1e0.png)

然后我想换回 “微软雅黑”（这是一个原本 cnfonts 就能检测到的字体, 而且在添加自定义配置之前，是首选的默认字体）

然后我点击微软雅黑。

![image](https://user-images.githubusercontent.com/549126/147408581-77d5bc99-cef6-4ed7-a4a4-551e202cb36f.png)

**Comment by zw963** [comment]
我觉得你新加的的 cnfonts--fontspec-valid-p 函数无法处理原本就正常显示的那些字体。

**Comment by tumashu** [comment]
我这边可以识别微软雅黑，fc-list看看雅黑的名字是什么

**Comment by zw963** [comment]
> 

好吧，这就有点奇怪了，我根本没装微软雅黑，但是如果我移除了 cnfonts-personal-fontnames 变量的设置，并且删除了之前保存的 config, 它的确选择的是微软雅黑。

![image](https://user-images.githubusercontent.com/549126/147408811-15d04a4d-191f-4909-a549-6b02e0cb0f3b.png)

我猜这个字体来自于这个组合字体。

```sh
 ╰─ $ fc-list |grep -i yahei
/home/zw963/.local/share/fonts/YaHeiMonacoHybrid.ttf: YaHei Monaco Hybird:style=Regular,Normal,obyčejné,Standard,Κανονικά,Normaali,Normál,Normale,Standaard,Normalny,Обычный,Normálne,Navadno,Arrunta
/home/zw963/.local/share/fonts/yaheiInconsolata.otf: yaheiInconsolata:style=Regular,Normal,obyčejné,Standard,Κανονικά,Normaali,Normál,Normale,Standaard,Normalny,Обычный,Normálne,Navadno,Arrunta,yaheiInconsolata
```

**Comment by tumashu** [comment]
有可能，因为emacs字体本身有fallback机制

**Comment by zw963** [comment]
我重新设置了下我的配置：

```cl
(defconst cnfonts-personal-fontnames
 '(;; 英文字体
   ("Fira Code Retina")
   ;; 中文字体
   ("微软雅黑")
   ;; EXT-B 字体
   ()
   ;; Symbol 字符字体
   ()
   ;; Emacs 社区配置中，用于装饰的字符使用的字体
   ()))
```

现在， Fira Code Retina 和 微软雅黑 一起工作了。

但是如果我选择了微米黑，然后想再选择回去，就不行了。

![image](https://user-images.githubusercontent.com/549126/147408969-a556fc82-f2f9-4ada-9d10-ef9bb6929e3e.png)

**Comment by tumashu** [comment]
你本身要安装雅黑这个字体，NA代表这个字体对cnfonts来说是不可用的，或者说找不到

**Comment by tumashu** [comment]
你应该添加YaHei Monaco Hybird这个名称

**Comment by zw963** [comment]
> 你应该添加YaHei Monaco Hybird这个名称

哦，微软雅黑，几个汉字，是硬变编码的吗？

**Comment by zw963** [comment]
这几个汉字确实可以激活微软雅黑，例如，用下面的配置，就自动选择了雅黑 和 Fira Code Retina

(defconst cnfonts-personal-fontnames
 '(;; 英文字体
   ("Fira Code Retina")
   ;; 中文字体
   (
    ;; "霞鹜文楷等宽"
    )
   ;; EXT-B 字体
   ()
   ;; Symbol 字符字体
   ()
   ;; Emacs 社区配置中，用于装饰的字符使用的字体
   ()))

**Comment by zw963** [comment]
如果选择使用 `YaHei Monaco Hybird` 的话，基本上就不需要 cnfonts 了，因为这个字体对的挺齐的。

https://github.com/maxsky/Yahei-Monaco-Hybrid-Font

**Comment by tumashu** [comment]
对，cnfonts自带一些常见的字体，要用的前提是你安装了这个字体，NA的标记要去掉。

在 2021-12-26 21:13:54，"Billy.Zheng" ***@***.***> 写道：


你应该添加YaHei Monaco Hybird这个名称

哦，微软雅黑，几个汉字，是硬变编码的吗？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
