### ISSUE TITLE
cnfonts 在 Emacs 29 中无效

### ISSUE THREAD

**Issue by blldw** [tumashu/cnfonts#132]
一不小心将 Emacs 从 28.0 升级到了 29.0，发现 cnfonts 不再有效，表现为 cnfonts-ui 界面中切换字体无效，在对齐界面中调整字体大小也无效。估计是 Emacs 29 升级后某方面的变更与 cnfonts 工作机制冲突了。

Emacs 29.0 在 Ubuntu 18.04 和 20.04 下均出现该问题，在 Windows 下也存在同样问题，而在 Emacs 28.0 下均能正常工作。

**Comment by tumashu** [comment]
真的假的？ 最近也没看到 emacs 有什么字体相关的变更啊

**Comment by blldw** [comment]
> 真的假的？ 最近也没看到 emacs 有什么字体相关的变更啊

真的, 你可以测试一下~

**Comment by tumashu** [comment]
试试最新代码

**Comment by blldw** [comment]
就我测试结果而言，现在能在 cnfonts-ui 界面下：
1. 能有效切换英文，但切换中文没变化；
2. 在 “对齐” 选项卡中，“测试” 按钮有效，但调节相应字号还是没变化，而且出现很多的中文乱码。

**Comment by tumashu** [comment]
确实

**Comment by tumashu** [comment]
我试着修复了一下，再试试

**Comment by blldw** [comment]
perfect，已解决~

**Comment by tumashu** [comment]
退回到原来的版本了， 因为 emacs git 修复了bug，

**Comment by blldw** [comment]
哦，我还想着提醒更新一下 ELPA/MELPA 上的版本来着，这么说的话就不用了~

**Comment by tumashu** [comment]
是啊，这个事折腾了我好几天，吐血

**Comment by blldw** [comment]
理解~
