### ISSUE TITLE
讨论：对中文字体的 weight 和 slant 设置是有意为之的吗？

### ISSUE THREAD

**Issue by mkvoya** [tumashu/cnfonts#133]
代码里面对于英文之外的字体的 `weight` 和 `slant` 都设置为了 `normal` ，
我在最近使用 TangerJinKai 的时候发现 `normal` 会导致中文字体设置失效，改成 `medium` 才能正常显示。

https://github.com/tumashu/cnfonts/blob/dfa75df98625cbd9d563d833d4238c94cca5d22c/cnfonts.el#L683-L707

在 issue 里面也看到一些 中文 无法加粗和斜体的问题，我试着把除了英文之外的默认 `weight` 和 `slant` 去掉了，然后发现这些问题似乎就解决了（效果如下图）。不知之前的默认值是否有某种特殊考虑？比如对齐之类？

<img width="146" alt="image" src="https://user-images.githubusercontent.com/10482293/144698045-ccc30c43-21aa-4d41-ba45-18bb2c1a549f.png">

**Comment by tumashu** [comment]
我更新一下，试上几天看看有没有人反馈其它问题

**Comment by tumashu** [comment]
这个包的核心代码是我很久以前写的，那时候还是初学者，我估计当时的代码就是参考别人，或者试出来的，哈哈😀

**Comment by tumashu** [comment]
估计没什么事，这个issue关了
