### ISSUE TITLE
define-obsolete-variable-alias: Wrong number of arguments: (3 . 4), 2

### ISSUE THREAD

**Issue by okysh** [tumashu/cnfonts#139]
### 我使用的配置框架：

```https://github.com/redguardtoo/emacs.d```

### 我的配置：~/.custom.el

```(require-package 'cnfonts)```

### 我的版本
- cnfonts 0.9.1
- redguardtoo develop
- win10
- emacs 28.1 x64
---

启动后当我执行任何一个cnfonts-*的命令，都会得到以下的错误提示：

> Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2) [2 times]
define-obsolete-variable-alias: Wrong number of arguments: (3 . 4), 2Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2) [2 times]
define-obsolete-variable-alias: Wrong number of arguments: (3 . 4), 2

**Comment by tumashu** [comment]
奇怪了，我搜了一下，cnfonts 没有调用 define-obsolete-variable-alias 啊

**Comment by tumashu** [comment]
这个无法复现，先关闭了
