### ISSUE TITLE
[Bug] doom Emacs  开启 chinese 模块，表格无法对齐

### ISSUE THREAD

**Issue by harisonkhlil** [tumashu/cnfonts#150]
## 操作流程

开启 doom Emacs 的 Chinese 模块，新建一个 org 文件，编写相关的信息，最后使用 `C-c C-c` 对齐

## 预期目标（打开前）

成功对齐：
![CleanShot 2023-10-19 at 16 40 47@2x](https://github.com/tumashu/cnfonts/assets/70578017/607c6d90-3d8b-44c6-b0ab-219ac8dcb7f4)

## 实际效果（关闭后）

如图所示：
![CleanShot 2023-10-19 at 16 35 42@2x](https://github.com/tumashu/cnfonts/assets/70578017/578d6f15-a1d4-4f81-a526-6ad594e875eb)

**Comment by tumashu** [comment]
doom 有自己的字体设置，估计会和cnfonts会冲突，如果不了解 emacs 机制，不建议混用。

**Comment by Jane-fine** [comment]
有相同的状况。
发现是 chinese 模块中的 pangu-spacing-mode 在启用时增加了一个 overlay 导致的。至于 overlay 为什么会导致这个对齐问题，看不懂代码，猜测 emacs 中表格对齐部分的 code 没有考虑 overlay 的因素。
最简单的解决方案是：在表格输入时遵守「盤古之白」，给英文和中文之间手动增加一个空格。用“真空格”替代那个 overlay。
下面贴一个 pangu-spacing 模块的演示动图
https://github.com/coldnew/pangu-spacing/raw/master/screenshot/screenshot.gif
