### ISSUE TITLE
开启 cnfonts-mode 之后, 显示 emoji 失败.

### ISSUE THREAD

**Issue by zw963** [tumashu/cnfonts#151]
正常情况甚至零字体配置的下,  Emacs 29.2 可以正确显示 emoji 的, 甚至无需设定下面的配置. (系统已安装 Noto Color Emoji 字体)

```cl
(when (member "Noto Color Emoji" (font-family-list))
  (set-fontset-font
   t 'symbol (font-spec :family "Noto Color Emoji") nil 'prepend))
```
![image](https://github.com/tumashu/cnfonts/assets/549126/81e53311-bcd1-445a-9ba8-1376caaccd12)

但是, 一旦开启 cnfonts-mode,  emoji 就无法正确显示了.

![image](https://github.com/tumashu/cnfonts/assets/549126/ce1e5520-07f1-47f5-b9d7-74d02ed2524a)

我也尝试过强制使用下面的代码来让 Noto Color Emoji" 变得可选择的, 并通过编辑界面, 将它设定为默认 emoji 字体, 但是问题依旧.

```cl
(defconst cnfonts-personal-fontnames
 '(;; 英文字体
   ("Fira Code Retina")
   ;; 中文字体
   (
    "霞鹜文楷等宽"
    )
   ;; EXT-B 字体
   ()
   ;; Symbol 字符字体
   ("Noto Color Emoji")
   ()
   ))
```

谢谢.

**Comment by scinart** [comment]
试一下[这个](https://github.com/scinart/cnfonts/commit/0abdc86d7371a4bd033e704584c5ad252229863e)？
```diff
    ;; 设置中文字体，注意，不要使用 'unicode charset,
    ;; 否则上面的英文字体设置将会失效。
    (when (cnfonts--fontspec-valid-p chinese-fontspec)
-      (dolist (charset '(kana han cjk-misc bopomofo gb18030))
+      (dolist (charset '(kana han cjk-misc bopomofo))
        (set-fontset-font
         "fontset-default"
         charset chinese-fontspec)))
```

**Comment by zw963** [comment]
> 试一下[这个](https://github.com/scinart/cnfonts/commit/0abdc86d7371a4bd033e704584c5ad252229863e)？
> 
> ```diff
>     ;; 设置中文字体，注意，不要使用 'unicode charset,
>     ;; 否则上面的英文字体设置将会失效。
>     (when (cnfonts--fontspec-valid-p chinese-fontspec)
> -      (dolist (charset '(kana han cjk-misc bopomofo gb18030))
> +      (dolist (charset '(kana han cjk-misc bopomofo))
>         (set-fontset-font
>          "fontset-default"
>          charset chinese-fontspec)))
> ```

因为不显示 emoji, 我现在不用 cnfonts 了, 不过我专门试了下, 真的工作啊, 也许你该提一个 PR ?
