### ISSUE TITLE
Unable to find cnfonts in melpa

### ISSUE THREAD

**Issue by seagle0128** [tumashu/cnfonts#72]
I am unable to find `cnfonts` package in melpa, while the `chinese-fonts-setup` package is still there.

**Comment by tumashu** [comment]
Yes， this is need time

**Comment by tumashu** [comment]
https://github.com/melpa/melpa/pull/4871

**Comment by seagle0128** [comment]
Thanks for the update.

**Comment by seagle0128** [comment]
Show the incompatible packages in the list due to https://github.com/tumashu/cnfonts/commit/606ff23ab4984dd5a547ce73c7e46713590fdb99

**Comment by tumashu** [comment]
不要着急， 等 melpa 管理员合并后再说。。。。。 ：-）

**Comment by tumashu** [comment]
ok

**Comment by seagle0128** [comment]
Thanks! It works.

**Comment by tumashu** [comment]
不客气，我还要感谢同学提交 issue 呢。

**Comment by seagle0128** [comment]
@tumashu 客气，都是Emacs同好，多交流。
