### ISSUE TITLE
如何在org mode的ditaa环境中实现中英文  字符  等宽

### ISSUE THREAD

**Issue by QiangF** [tumashu/cnfonts#75]
我用Ditaa画图，如果字符是英文，先把文字在对应位置输入，然后用artist mode画框和箭
头，非常方便。但是中文就不行了，如果中英文对齐了，ditaa都输出并没有对齐，参照这
个问题：
https://emacs-china.org/t/ditaa/2392

我发现如果一个中文字符对应一个英文字符则可以对齐，如下例：

    #+BEGIN_SRC ditaa :file .//hello-world.png
    +-----+
    |你好   |
    +-----+
    #+END_SRC

所以有这个问题，如果不行如何写一个命令，在我画图时，实现buffer的中英文  字符  等
宽，完了切换回去？

**Comment by tumashu** [comment]
这似乎是 ditaa 的问题， 一个解决方案就是： 写一个 block filter， 将对齐的图表转换为ditaa识别的图表

**Comment by tumashu** [comment]
用plantuml吧，感觉也支持ditaa

**Comment by QiangF** [comment]
但是plantuml的ditaa好像也绕不过这个问题。找到下面这个修改字体的设置：

    (defvar emacs-english-font "DejaVu Sans mono"
    "The font name of English.")

    (defvar emacs-cjk-font "Microsoft Yahei"
    "The font name for CJK.")

    (defvar emacs-font-size-pair '(15 . 18)
    "Default font size pair for (english . chinese)")

    (defvar emacs-font-size-pair-list
    '(( 5 .  6) (10 . 12)
        (13 . 16) (15 . 18) (17 . 20)
        (19 . 22) (20 . 24) (21 . 26)
        (24 . 28) (26 . 32) (28 . 34)
        (30 . 36) (34 . 40) (36 . 44))
    "This list is used to store matching (englis . chinese) font-size.")

    (defun font-exist-p (fontname)
    "Test if this font is exist or not."
    (if (or (not fontname) (string= fontname ""))
        nil
        (if (not (x-list-fonts fontname)) nil t)))

    (defun set-font (english chinese size-pair)
    "Setup emacs English and Chinese font on x window-system."

    (if (font-exist-p english)
        (set-frame-font (format "%s:pixelsize=%d" english (car size-pair)) t))

    (if (font-exist-p chinese)
        (dolist (charset '(kana han symbol cjk-misc bopomofo))
            (set-fontset-font (frame-parameter nil 'font) charset
                            (font-spec :family chinese :size (cdr size-pair))))))

    ;; Setup font size based on emacs-font-size-pair
    (set-font emacs-english-font emacs-cjk-font emacs-font-size-pair)

    (defun emacs-step-font-size (step)
    "Increase/Decrease emacs's font size."
    (let ((scale-steps emacs-font-size-pair-list))
        (if (< step 0) (setq scale-steps (reverse scale-steps)))
        (setq emacs-font-size-pair
            (or (cadr (member emacs-font-size-pair scale-steps))
                emacs-font-size-pair))
        (when emacs-font-size-pair
        (message "emacs font size set to %.1f" (car emacs-font-size-pair))
        (set-font emacs-english-font emacs-cjk-font emacs-font-size-pair))))

    (defun increase-emacs-font-size ()
    "Decrease emacs's font-size acording emacs-font-size-pair-list."
    (interactive) (emacs-step-font-size 1))

    (defun decrease-emacs-font-size ()
    "Increase emacs's font-size acording emacs-font-size-pair-list."
    (interactive) (emacs-step-font-size -1))

    (defvar ditaa-font-active nil)
    (defun toggle-ditaa-font ()
    "Font size pair when draws with artist mode (english . chinese)"
    (interactive)
    (if ditaa-font-active
        (set-font emacs-english-font emacs-cjk-font '(20 . 12))
        (set-font emacs-english-font emacs-cjk-font emacs-font-size-pair))
    (setq ditaa-font-active (not ditaa-font-active)))

    (set-font emacs-english-font emacs-cjk-font emacs-font-size-pair)
    (global-set-key (kbd "C-=") 'increase-emacs-font-size)
    (global-set-key (kbd "C--") 'decrease-emacs-font-size)

**Comment by tumashu** [comment]
你还不如新建一个 cnfonts profile， 专门用于ditaa呢。更省事

**Comment by whatacold** [comment]
@QiangF 请问你上面提到的这个配置了之后， ditaa 画出来图片，框能对齐吗？（emacs china那个帖子框不对齐）

**Comment by QiangF** [comment]
可以！

**Comment by brioglade** [comment]
@whatcold  请问你的用了上面配置后再用ditaa也能画出图了吗？@QiangF  上面那段配置如果是spacemacs 放到哪个位置？

**Comment by whatacold** [comment]
@brioglade ditaa 没怎么画过图了，上面配置我没试过，帮不上不好意思。

**Comment by QiangF** [comment]
@brioglade 我不会spacemacs呢 ditaa中文支持不好，建议用 aafigure
