### ISSUE TITLE
ubuntu mono 字体有些字号无法对齐

### ISSUE THREAD

**Issue by amosbird** [tumashu/cnfonts#76]
中文我用的`      [X] 文泉驿等宽微米黑`    

英文字号 10，12.5，14，15无法对齐

**Comment by tumashu** [comment]
应该不会吧，我到现在还没碰到对不齐的等宽字体

**Comment by amosbird** [comment]
我也不知道，不过用monaco就没问题

**Comment by tumashu** [comment]
你有没有用那个对齐设置，调整对齐？

**Comment by amosbird** [comment]
用了，就是用那个工具，试了所有的字号大小都对不齐，才来提的issue

**Comment by tumashu** [comment]
我这边可以：

![5xz_ fr qya _ xdk wl v9](https://user-images.githubusercontent.com/67725/30532291-1470a7cc-9c86-11e7-9ca4-a6d6a6901d36.png)
![6f0ewu_o3r0sp4lxzb33 ua](https://user-images.githubusercontent.com/67725/30532293-173de8f2-9c86-11e7-85be-fd138d06810e.png)
![t zoar m07 16l k 2jar](https://user-images.githubusercontent.com/67725/30532296-193509b0-9c86-11e7-8832-b5c00801c4a9.png)

**Comment by amosbird** [comment]
好吧，我再想别的办法，谢谢。
