### ISSUE TITLE
这个 stackexchange 描述的方法, 是不是就不用cnfonts用户自己去 试验要对齐的中英文字体大小了， 可以直接给出？

### ISSUE THREAD

**Issue by aligua** [tumashu/cnfonts#78]
https://emacs.stackexchange.com/questions/5495/how-can-i-determine-the-width-of-characters-on-the-screen

我根据那个里面的试验了一下， 好像能给出中英文的像素宽度

把一个buffer设置成某一个大小的字体
(defun zjl-test-set-buffer-face ()
  (buffer-face-set '(:family "Source Code Pro" :height 160)))

(defun zjl-test-get-font-width () 
  "Return the width in pixels of a character in the current
window's default font.  More precisely, this returns the
width of the letter ‘m’.  If the font is mono-spaced, this
will also be the width of all other printable characters."
  (let ((window (selected-window))
        (remapping face-remapping-alist))
    (with-temp-buffer
      (make-local-variable 'face-remapping-alist)
      (setq face-remapping-alist remapping)
      (set-window-buffer window (current-buffer))
      (zjl-test-set-buffer-face)
      (insert "m")
      ;; (insert "号") 可以试验中文的字体的大小
      (aref (aref (font-get-glyphs (font-at 1) 1 2) 0) 4))))

;;这个只是我随便写的， 算frame的显示某一个font的子个数， 不过貌似实际显示的要比算的少一个
(defun zjl-test-get-helm-width-of-spefic-font ()
  (/ (frame-pixel-width) (zjl-test-get-font-width)))

**Comment by tumashu** [comment]
这个方式倒是有可能, 但不知道效果怎么样...

**Comment by aligua** [comment]
tumashu <notifications@github.com>于2017年10月4日 周三上午7:50写道：

**Comment by aligua** [comment]
我昨天试的计算字宽度 （我想helm）多显示一些内容 把字体缩小了 然后需要估计 helm buffer 一行的字数
发现这个估计的还挺准的。就是发现中文的不一样大。 就想起了可以用到你这个对齐啦。 不知道有没有坑
jianli zhao <jianlizhao1@gmail.com>于2017年10月4日 周三上午10:45写道：

**Comment by tumashu** [comment]
这个功能我决定放弃了， 原因是:
1. 如果单独将这个功能做成一个 package， 可能代码更少，维护更简单
2. 我实在想不出如何将这个功能和 cnfonts 完美的集成

**Comment by aligua** [comment]
OK,  不用有压力:) 无条件支持你的决定， 我有的用就很开心了。谢谢
