### ISSUE TITLE
不兼容 Emacs26

### ISSUE THREAD

**Issue by seagle0128** [tumashu/cnfonts#81]
GNU Emacs 26.0.90, macOS 10.13.1, Windows 10

步骤：
1. 启动 Emacs。
2. 在`init.el`中加入`(desktop-save-mode 1)`，最大化窗口。
3. 安装 `cnfonts`，并加入配置
```elisp
(cnfonts-enable)
(setq cnfonts-profiles
        '("program1" "program2" "program3" "org-mode" "read-book"))
  (setq cnfonts--profiles-steps '(("program1" . 4)
                                  ("program2" . 5)
                                  ("program3" . 3)
                                  ("org-mode" . 6)
                                  ("read-book" . 8)))
```
3. 关闭再重启。

结果发现窗口不能按照预期恢复，大小和位置都有问题。最大化的窗口变小了一圈，在 macOS 和 Windows 上都如此，但用 Emacs 24.5 和25.3均正常。如果我用`cnfonts-insert-fonts-configure`直接插入相同的字体设置并禁用掉`cnfonts`，所有一切正常，非常奇怪。

Emacs26正式版即将发布，请修复该问题。谢谢！

**Comment by seagle0128** [comment]
刚测试发现，如果使用该配置，窗口恢复正常。
`(setq cnfonts-keep-frame-size nil)`

**Comment by tumashu** [comment]
```
 cnfonts-keep-frame-size
```
这个变量是为了让 emacs 启动的过程中， 窗口大小保持不变，别变大变小的让人烦心

**Comment by seagle0128** [comment]
Windows 26 中似乎 `cnfonts-keep-frame-size`失效了，去掉反而正常。

**Comment by tumashu** [comment]
我测试了一下， 似乎没什么问题， 我倒是感觉可能是你使用的姿势不对， 这个 keep frame 是确保启动的时候， 窗口大小一直保持窗口刚刚出现时的大小， 和 save desktop 保存的窗口大小没有关系， 这种情况，你就应该 setq cnfonts-keep-frame-size nil

**Comment by tumashu** [comment]
以前你可以用，也许是 save-desktop 非常早的起作用。。。。。
