### ISSUE TITLE
frame-zoom 和 font-scale 操作后没有跟着变化

### ISSUE THREAD

**Issue by driftcrow** [tumashu/cnfonts#83]
调整字大小或者整个FRAME 缩放后不能跟着变化

**Comment by tumashu** [comment]
?

**Comment by driftcrow** [comment]
就是text-scale-adjust 和 zoom-all-frame-in/out 操作后改变字体大小时会改变英文和中文所有字体的大小，而cnfont没能进行自动调整来继续实现对齐

因为这种操作还是比较多的，在做演示等场景时会很需要，所以希望能增加这个能自动调整的特性

**Comment by tumashu** [comment]
是这两个命令吗？
```
cnfonts-increase-fontsize | 增大字号
cnfonts-decrease-fontsize | 减小字号


```

**Comment by driftcrow** [comment]
哦，看来我没有用这两个命令。这两个命令可以解决我的问题了。谢谢^_^

**Comment by driftcrow** [comment]
不过还有个问题，不知道如何复原字体大小，就是把字体 调大或调小很多的时候，如何快速回到最初设定的大小 ，cnfonts-reset-fontsize 函数有吗？ @tumashu

**Comment by driftcrow** [comment]
另外就是edit-profile时调整字体大小的快捷键 C-up 和 C-down 有MACOS中和系统热键冲突，无法操作，能不能调整下 @tumashu

**Comment by tumashu** [comment]
```
另外就是edit-profile时调整字体大小的快捷键 C-up 和 C-down 有MACOS中和系统热键冲突，无法操作，能不能调整下
```
(define-key cnfonts-ui-mode-map (kbd "YOUR-KEY") 'cnfonts-ui-decrease-align)

试一试

**Comment by tumashu** [comment]
···
cnfonts-reset-fontsize
···

cnfonts 当前的设计师： 调整字体后就自动保存设置， 如果要添加这个命令，首先需要添加一个新的配置选项，来保存需要 reset 的数值，并且提供一种方式设置reset的值，感觉就非常麻烦了，毕竟大多数情况，大家不会频繁的放大缩小字体

**Comment by driftcrow** [comment]
嗯，谢谢你的耐心回复，还有cnfonts很好用
