### ISSUE TITLE
能仅仅针对orgmode文件有效吗

### ISSUE THREAD

**Issue by ghost** [tumashu/cnfonts#84]
如题，在别的例如c-mode下面我不想这个生效，只想在编辑的org文件里面才启用这个配置

**Comment by tumashu** [comment]
这是为什么？

**Comment by chen-chao** [comment]
可以参考这个 https://zcodes.net/2016/08/22/emacs-notes-config.html，给org table专门设一个fontset.

**Comment by forrestchang** [comment]
@chen-chao 参考链接失效了。

> 可以参考这个
> 
> https://zcodes.net/2016/08/22/emacs-notes-config.html
> 
> 给org table专门设一个fontset.

**Comment by BobCromwell** [comment]
按 https://github.com/chen-chao/.emacs.d/blob/e1bf4f31c23c341830c8d47ccb6076c955922bf0/settings/theme-settings.el  的代码搞了一下，org table 基本对齐了，但 org mode 标题字体大小都一样了，还是很不习惯，不知道为什么会影响表格之外的地方

**Comment by chen-chao** [comment]
> 按 https://github.com/chen-chao/.emacs.d/blob/e1bf4f31c23c341830c8d47ccb6076c955922bf0/settings/theme-settings.el 的代码搞了一下，org table 基本对齐了，但 org mode 标题字体大小都一样了，还是很不习惯，不知道为什么会影响表格之外的地方

只设置 org table 的 face attribute 应该不会影响其他内容?

```elisp
(set-face-attribute 'org-table nil :fontset your-fontset)
```

**Comment by chen-chao** [comment]
> @chen-chao 参考链接失效了。
> 
> > 可以参考这个
> > https://zcodes.net/2016/08/22/emacs-notes-config.html
> > 给org table专门设一个fontset.

主要的 code snippet, 可供参考: 
```elisp
;; 单独设置一个 fontset, 避免被影响
;; 核心思想就是挑选配对的中文和英文字体，然后分别设置期大小，
;; 让一个汉字的宽度正好是两个英文字符的宽度。
(setq fontset-orgtable
      (create-fontset-from-ascii-font "Consolas 11"))
(dolist (charset '(han symbol cjk-misc))
  (set-fontset-font fontset-orgtable charset
		    (font-spec :family "Microsoft Yahei"
			       :size 12.0)))

(add-hook 'org-mode-hook
	  '(lambda ()
	     (set-face-attribute 'org-table nil
				 :font "Consolas 11"
				 :fontset fongset-orgtable)))
```

**Comment by BobCromwell** [comment]
> > @chen-chao 参考链接失效了。
> > > 可以参考这个
> > > https://zcodes.net/2016/08/22/emacs-notes-config.html
> > > 给org table专门设一个fontset.
> 
> 原来的 code snippet, 可供参考:
> 
> ```emacs-lisp
> ;; 单独设置一个 fontset, 避免被影响
> ;; 核心思想就是挑选配对的中文和英文字体，然后分别设置期大小，
> ;; 让一个汉字的宽度正好是两个英文字符的宽度。
> (setq fontset-orgtable
>       (create-fontset-from-ascii-font "Consolas 11"))
> (dolist (charset '(han symbol cjk-misc))
>   (set-fontset-font fontset-orgtable charset
> 		    (font-spec :family "Microsoft Yahei"
> 			       :size 12.0)))
> 
> (add-hook 'org-mode-hook
> 	  '(lambda ()
> 	     (set-face-attribute 'org-table nil
> 				 :font "Consolas 11"
> 				 :fontset fongset-orgtable)))
> ```
> 
> 和 cnfonts 想法都是一样的, 只不过这里单独给 org table 设置了字体.

改了一个 typo，我喜欢字大点，mac 上可用

`;; 单独设置一个 fontset, 避免被影响
;; 核心思想就是挑选配对的中文和英文字体，然后分别设置期大小，
;; 让一个汉字的宽度正好是两个英文字符的宽度。
(setq fontset-orgtable
      (create-fontset-from-ascii-font "Monaco 19"))
(dolist (charset '(han symbol cjk-misc))
  (set-fontset-font fontset-orgtable charset
		    (font-spec :family "Hiragino Sans GB W3"
			       :size 22)))

(add-hook 'org-mode-hook
	  '(lambda ()
	     (set-face-attribute 'org-table nil
				 :font "Monaco 19"
				 :fontset fontset-orgtable)))`

**Comment by WangLeshan** [comment]
> 				 :fontset fongset-orgtable)))

是 fontset-orgtable， g -->t
