### ISSUE TITLE
调用cnfonts-*-fontsize调整字体大小时，中文字体大小没有恢复。

### ISSUE THREAD

**Issue by xueshumeng** [tumashu/cnfonts#89]
调用函数cnfonts-increase-fontsize字体增大之后，再次调用函数cnfonts-decrease-fontsize将字体缩小，中文字体没有恢复这两步操作之前的大小。

**Comment by tumashu** [comment]
发个gif看看

**Comment by yxsongbo** [comment]
cnfonts-increase-fontsize 这个函数有没有绑定什么快捷键？

**Comment by yxsongbo** [comment]
C-x  C-+ 增大字号的时候，只有英文和数字增大，中文没有一起增大，要怎么让所有文字同时增大呢？

**Comment by tumashu** [comment]
cnfonts-increase-fontsize 默认没有绑定任何按键，用户自己绑定吧, 英文和中文本来就是自动增加减小，不知道你那边为什么会遇到这种情况,  运行 cnfonts-edit-profile, 截图看看

**Comment by tumashu** [comment]
可能是cnfonts没有找到合适的中文字体，所以emacs使用fallback机制来显示中文，你运行一下cnfonts-edit-profile,然后截一张中文字体设置的图看看

**Comment by yxsongbo** [comment]
![_20181223191750](https://user-images.githubusercontent.com/135945/50383059-83cd6980-06e7-11e9-9a6e-db7826e337de.png)


非常感谢您得热心指教

**Comment by yxsongbo** [comment]
点了之后没有反应？

**Comment by yxsongbo** [comment]
![_20181223194902](https://user-images.githubusercontent.com/135945/50383307-dad53d80-06eb-11e9-8ce4-5eb6061b8d0b.png)

**Comment by tumashu** [comment]
我感觉你用错命令了。。。你可能不是运行的cnfonts自带的增大缩小命令

**Comment by yxsongbo** [comment]
请问怎么将cnfonts自带的增大缩小命令绑定到C-x C-+呢？

**Comment by tumashu** [comment]
这个自己baidu一下吧...
