### ISSUE TITLE
question:  org-table 自动对齐 怎么把中文字符和英文字符平等对待

### ISSUE THREAD

**Issue by QiangF** [tumashu/cnfonts#90]
初衷是用ditaa画流程图，中英文等宽时刚好，线条是对上的（没有错位）。又想用org-table自动对齐，中英文等宽时，自动对齐没有齐，
如：
    | \<c4\> |\<c4\> |
    | 混料 | 验   |

用这个命令实现中英文等宽：

    (set-font emacs-english-font emacs-cjk-font '(20 . 12))

**Comment by tumashu** [comment]
ditaa的问题

**Comment by QiangF** [comment]
这样貌似可以

    (defun ditaa-set-char-width ()
    (interactive)
    (while (char-table-parent char-width-table)
            (setq char-width-table (char-table-parent char-width-table)))
    (let ((table (make-char-table nil))
            (width 1))
        (dolist (range (unicode-char-range))
        (set-char-table-range table range width))
        (optimize-char-table table)
        (set-char-table-parent table char-width-table)
        (setq char-width-table table)))


    (defun ditaa-toggle-font ()
    "Font size pair when draws with artist mode (english . chinese)"
    (interactive)
    (if ditaa-font-active
        (progn (message "ditaa font active")
               (ditaa-set-char-width)
               (set-font emacs-english-font emacs-cjk-font '(20 . 12)))
        (progn (ditaa-unset-char-width)
               (set-font emacs-english-font emacs-cjk-font emacs-font-size-pair)))
    (setq ditaa-font-active (not ditaa-font-active)))
