### ISSUE TITLE
daemon模式emacsclient启动后字体设置不生效

### ISSUE THREAD

**Issue by feileb** [tumashu/cnfonts#94]
我使用的是spacemacs，开机自动执行emacs --daemon，然后使用emacsclient -c -a ""启动emacs
已经添加了cnfonts-set-font-first-time到下面两个hook
after-make-frame-functions
windows-setup-hook

启动后字体没有生效，目前的解决办法是通过ctrl加鼠标滚轮调用cnfonts-in(de)crease-fontsize
请问有没有好的解决办法？

**Comment by tumashu** [comment]
spaceman 有自己的字体设置，会不会覆盖了呀？

**Comment by feileb** [comment]
正常启动的时候spacemacs的user-config里面会调用cnfonts-enable，这种情况是正常的，
daemon模式下同样的配置就没有效果。
即使启动后我再次调用cnfonts-enable或者先cnfonts-disable,再cnfonts-enable都不会生效了。

**Comment by tumashu** [comment]
把 cnfonts-enable 添加到 ~/.emacs 可以不， 说的简单点，就是在显示 frame 之前要加载 cnfonts 的设置，不然就不会有效

**Comment by feileb** [comment]
我是直接加在~/.spacemacs文件里面的，应该是从~/.emacs.d/init.el调过来的，没有.emacs文件，我新建一个.emacs测试，就不会加载~/.emacs.d/init.el的配置了。

**Comment by tumashu** [comment]
无论加到哪里，只要确保 frame 创建之前加载了设置，应该就可以

**Comment by vrboxing** [comment]
@feileb ，你的问题解决了吗？我现在也是遇到这个问题搞不定，看过好多写法都不行啊

**Comment by tumashu** [comment]
我靠，测试的好仔细，厉害。。。。

**Comment by sd44** [comment]
我使用的是创建cnfonts layer的方式来实现配置，经测试daemon和普通模式下均可正常使用。
首先运行create-layer命令，我创建的是layer名为sd44

然后编辑sd44目录下的packages.el，内容如下

```
(defconst sd44-packages
  '(cnfonts)
  )

(defun sd44/init-cnfonts ()
  (use-package cnfonts)
  (cnfonts-enable)
  ;; 让 spacemacs mode-line 中的 Unicode 图标正确显示。
  (cnfonts-set-spacemacs-fallback-fonts)
  (setq cnfonts-use-face-font-rescale t)
  )
;;; packages.el ends here

```

这样就可以正常使用了。
