### ISSUE TITLE
cnfonts-ui 对齐tab如何看当前使用的是哪种字号？

### ISSUE THREAD

**Issue by whatacold** [tumashu/cnfonts#95]
比如我调整对齐的时候，在英文字号16这一行点测试，然后点击+/-调整中文字号，对齐了之后，点击“对齐设置完成”，页面字体却又变小了。（我的直觉反应是此时应该使用16这一行的字号，不知道哪里理解不对。）

**Comment by tumashu** [comment]
不是， 对齐设置是为了建立一个设置库，告诉cnfonts 每一个字号所需要的对齐信息， 至于你默认使用哪个字号，用 cnfonts-increase-fontsize 或者 cnfonts-decrease-fontsize 来设置

**Comment by whatacold** [comment]
原来如此，多谢。
