### ISSUE TITLE
启用cnfont后，modeline 图标显示不正常

### ISSUE THREAD

**Issue by driftcrow** [tumashu/cnfonts#98]
arch linux ，doom-emacs的配置，启动（自动或手动）cnfont修改文件后，修改标志的图标变的巨大。在MAC系统中同样的配置没有这个现像。不知道怎么去找问题。确定应该 是cnfont引起的冲突，因为关闭这个包就正常了。

![image](https://github.com/driftcrow/misc/raw/master/2018-10-24-1540345873_screenshot_881x227.jpg)

```
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1 (Jul 05, 2018)
- Doom: 2.0.9 (develop 9599ca3cf2e4be410a780d56bcc1d05dd6c7ae4a)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux folder 4.18.14-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 13 13:42:37 UTC 2018 x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion company (ivy +fuzzy) :ui doom doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) vc-gutter vi-tilde-fringe window-select :editor multiple-cursors rotate-text :emacs dired ediff electric hideshow imenu vc :tools editorconfig macos make pdf tmux upload :lang data emacs-lisp javascript latex ledger lua markdown (org +attach +babel +capture +export +present) plantuml (python +conda) sh web :app email irc (write +wordnut +langtool) :config default :private personal org chinese)
  packages:  (atomic-chrome cal-china-x cnfonts counsel-tramp diffview discover-my-major docker-tramp drag-stuff electric-operator fcitx graphviz-dot-mode keyfreq list-environment lsp-python org-brain (org-clock-budget :recipe (org-clock-budget :fetcher github :repo Fuco1/org-clock-budget)) org-clock-convenience org-fancy-priorities org-super-agenda org-web-tools org-wild-notifier orgit pinyinlib pipenv py-isort restart-emacs sx tldr try whitespace-cleanup-mode (yapfify :recipe (yapfify :fetcher github :repo JorisE/yapfify)) youdao-dictionary ztree)
  exec-path: (/opt/google-cloud-sdk/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /opt/anaconda/bin /opt/cuda/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/26.1/x86_64-pc-linux-gnu)
  ```
```

**Comment by tumashu** [comment]
建议问问看看 doom-emacs 的字体设置，doom-emacs好像是一套emacs配置，包含了特定的字体设置，冲突是正常的， 另外这个图标是某个字体吗?

**Comment by driftcrow** [comment]
嗯，可能是在Linux中安装的图标字体和状态行图标的字体冲突了，但是cnfont的hook可能是改变的主要原因。我慢慢查吧

**Comment by seagle0128** [comment]
cnfonts启用后导致 all-the-icons 字符集加载有问题，所以 modeline 图标就显示不正常了。有办法兼容 all-the-icons 吗？

**Comment by tumashu** [comment]
也许，不过我不使用 all-the-icons, 有兴趣的话你可以自己折腾折腾

**Comment by seagle0128** [comment]
我尝试了与 spacemacs fallback 类似的方法，但是发现对于某些字符集还是失效。暂时不用 cnfonts 了。

**Comment by hekinami** [comment]
for whom using cnfonts and doom-modeline(all-the-icons) together, we have a simple solution to make them coexist. Just configure your cnfonts in the following way.

(use-package cnfonts
:ensure t
:after all-the-icons
:hook (cnfonts-set-font-finish
. (lambda (fontsizes-list)
(set-fontset-font t 'unicode (font-spec :family "all-the-icons") nil 'append)
(set-fontset-font t 'unicode (font-spec :family "file-icons") nil 'append)
(set-fontset-font t 'unicode (font-spec :family "Material Icons") nil 'append)
(set-fontset-font t 'unicode (font-spec :family "github-octicons") nil 'append)
(set-fontset-font t 'unicode (font-spec :family "FontAwesome") nil 'append)
(set-fontset-font t 'unicode (font-spec :family "Weather Icons") nil 'append)))
:config
(cnfonts-enable))

**Comment by dalu98** [comment]
> for whom using cnfonts and doom-modeline(all-the-icons) together, we have a simple solution to make them coexist. Just configure your cnfonts in the following way.
> 
> (use-package cnfonts
> :ensure t
> :after all-the-icons
> :hook (cnfonts-set-font-finish
> . (lambda (fontsizes-list)
> (set-fontset-font t 'unicode (font-spec :family "all-the-icons") nil 'append)
> (set-fontset-font t 'unicode (font-spec :family "file-icons") nil 'append)
> (set-fontset-font t 'unicode (font-spec :family "Material Icons") nil 'append)
> (set-fontset-font t 'unicode (font-spec :family "github-octicons") nil 'append)
> (set-fontset-font t 'unicode (font-spec :family "FontAwesome") nil 'append)
> (set-fontset-font t 'unicode (font-spec :family "Weather Icons") nil 'append)))
> :config
> (cnfonts-enable))

I use your config and put it in my `config.el`, but when I open emacs, it shows:

    Error in private config: config.el, (error package.el is not yet initialized!)

If I change the `:ensure t` to `:ensure nil` or just delete that line, when I open my `config.el`
flycheck will show a warning on `use-package`:

    Unused lexical argument 'fontset-list'
    
Have you encountered the same problem? Thanks!  @hekinami

**Comment by hekinami** [comment]
@dalu98 

seemingly you didn't initialize your package.el before we use it.

evaluate

`(package-initialize)`

before all of your configuration code.

**Comment by dalu98** [comment]
> @dalu98
> 
> seemingly you didn't initialize your package.el before we use it.
> 
> evaluate
> 
> `(package-initialize)`
> 
> before all of your configuration code.

@hekinami I thought doom-emacs run this function by default when open it, so I didn't take this into consideration...

After I add it to my `init.el`, Emacs stopped reporting errors.

Thank you very much for your reply

**Comment by tumashu** [comment]
cnfonts-set-font-finish 应该是比较合适的解决方式
