### ISSUE TITLE
spacemacs配置cnfonts

### ISSUE THREAD

**Issue by ihaveadrame** [tumashu/cnfonts#99]
cnfonts很不错，但是spacemacs部分的教程暂时没有，这让一些人比较困扰，包括我。 经过一番查找资料，现将我的经验分享。
在 `dotspacemacs-additional-packages` 中添加 `cnfonts` , 另外需要将 `使用 cnfonts 生成 elisp 字体配置片断` 中生成的配置加入 `dotspacemacs/user-config`中即可，重启emacs大功告成。

**Comment by tumashu** [comment]
Sspacemacs 有自己内置的字体设置，所以如果想让 cnfonts 生效，就应该让 cnfonts 配置尽可能的延迟加载

**Comment by ihaveadrame** [comment]
@tumashu 嗯 user-config就是在layer加载完成后执行的

**Comment by tumashu** [comment]
那你直接 运行 confonts-enable 不就 OK 了？

**Comment by ihaveadrame** [comment]
@tumashu  spacemacs有个机制所有的mode要么是属于一个layer要么在
dotspacemacs-additional-packages中特别标识，否则会被自动清理掉。其实我issue中的第二部可选，只是个人偏好。
